name: Github pages
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Restore NPM cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-14-x-${{ github.ref }}

      - name: Install NPM Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VUE_APP_JOBSERM_ENDPOINT: https://api-jobserm-cjtim.cloud.okteto.net

      - run: npm test

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
